Add python 3.6 support back
hipe4ml/hipe4ml pull request #115
Opened 2021-02-15 17:15 UTC by fcatalan92

Turns out that having support for python 3.6 is nice (especially if you are using CentOS7). It looks possible now.

2021-02-15 17:49 UTC, mconcas commented
It is indeed nice and costless to support back py3.6.
I would also really like to avoid something like #104 again. 
Therefore, I suggest to pin the requirements versions, or at least of the annoying packages, e.g. shap and its dependencies (randomly installed thanks to `pip`'s resolution approach).
This, together with the adoption and pinpoitn of `awkward1` and  `uproot 4(?)` would set a stable standard for a while.

What do people think?

2021-02-15 17:51 UTC, mconcas requested changes

2021-02-15 17:51 UTC, mconcas commented on requirements.txt
> +shap>=0.38.1
What about
```suggestion
shap=0.38.1
```
?

2021-02-15 17:51 UTC, mconcas commented on setup.py
> +                      "xgboost>=1.2.1", "shap>=0.38.1", "bayesian-optimization>=1.2", "pyarrow>=2.0",
Same here:
```suggestion
                      "xgboost=1.2.1", "shap=0.38.1", "bayesian-optimization>=1.2", "pyarrow=2.0",
```
?

2021-02-15 17:51 UTC, mconcas commented on setup.py
> +                      "ipython>=6.0.0"],
```suggestion
                      "ipython=6.0.0"],
```

2021-02-15 17:51 UTC, mconcas commented on setup.py
> +        "dev": ["pylint>=2.4.4", "flake8>=3.7.9", "pytest>=5.3.4", "twine>=1.11.0", "setuptools>=53.0.0",
```suggestion
        "dev": ["pylint>=2.4.4", "flake8>=3.7.9", "pytest>=5.3.4", "twine>=1.11.0", "setuptools=53.0.0",
```

2021-02-16 10:15 UTC, fcatalan92 commented
@mconcas I bumped the packages, fixed the versions of the ones you suggested and of those needed to guarantee the python3.6 support. In the end, now almost all of them have the version fixed.
In a separate PR, I can work on migrating to uproot4 and removing some warnings.

2021-02-16 11:02 UTC, mconcas approved these changes

2021-02-16 11:03 UTC, mconcas approved these changes

2021-02-16 11:03 UTC, merged